// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
//dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVcXPTrLVGFtu_Imq4v4SNHPLXIPY-8hM',
    appId: '1:1041726255409:web:8bf87da19bda42a45e8010',
    messagingSenderId: '1041726255409',
    projectId: 'vitacare-633c9',
    authDomain: 'vitacare-633c9.firebaseapp.com',
    storageBucket: 'vitacare-633c9.firebasestorage.app',
    measurementId: 'G-Z2TMB8RQ24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg8Hrnfpg9_Tszhpjsy7wawHGrCMO1gq4',
    appId: '1:1041726255409:android:ed1939391a41200c5e8010',
    messagingSenderId: '1041726255409',
    projectId: 'vitacare-633c9',
    storageBucket: 'vitacare-633c9.firebasestorage.app',
  );
}
